apiVersion: v1
kind: Service
metadata:
  name: accountsnttpf
  labels:
    app: accountsnttpf
    service: accountsnttpf
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    service: accountsnttpf